const ExcelJS = require('exceljs')
const reportService = require('../services/reportService')

const COLORS = {
  ink: 'FF183247',
  accent: 'FF2F6F73',
  accentLight: 'FFE8F1F1',
  header: 'FF284C63',
  border: 'FFD4DEE5',
  stripe: 'FFF5F8FA',
  muted: 'FF5F7180',
  white: 'FFFFFFFF',
}

const thinBorder = {
  top: { style: 'thin', color: { argb: COLORS.border } },
  left: { style: 'thin', color: { argb: COLORS.border } },
  bottom: { style: 'thin', color: { argb: COLORS.border } },
  right: { style: 'thin', color: { argb: COLORS.border } },
}

const titleCase = value => String(value || '').replaceAll('_', ' ').replace(/\b\w/g, character => character.toUpperCase())
const dateText = date => new Date(date).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
const timeText = value => value ? new Date(value).toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' }) : ''

const addHeading = (sheet, lastColumn, subtitle, period, generatedAt, generatedBy, role) => {
  sheet.mergeCells(`A1:${lastColumn}2`)
  const title = sheet.getCell('A1')
  title.value = 'Visitor Pass Management System'
  title.font = { name: 'Aptos Display', size: 22, bold: true, color: { argb: COLORS.white } }
  title.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.ink } }
  title.alignment = { horizontal: 'center', vertical: 'middle' }
  sheet.getRow(1).height = 25
  sheet.getRow(2).height = 25

  sheet.mergeCells(`A3:${lastColumn}3`)
  const section = sheet.getCell('A3')
  section.value = subtitle
  section.font = { name: 'Aptos Display', size: 15, bold: true, color: { argb: COLORS.accent } }
  section.alignment = { horizontal: 'center', vertical: 'middle' }
  sheet.getRow(3).height = 25

  sheet.mergeCells(`A4:${lastColumn}4`)
  sheet.getCell('A4').value = `Report Period: ${period}`
  sheet.getCell('A4').font = { name: 'Aptos', size: 11, bold: true, color: { argb: COLORS.muted } }
  sheet.getCell('A4').alignment = { horizontal: 'center' }

  const columnCount = sheet.getColumn(lastColumn).number
  const middle = Math.ceil(columnCount / 2)
  const leftEnd = sheet.getColumn(middle).letter
  const rightStart = sheet.getColumn(middle + 1).letter
  sheet.mergeCells(`A5:${leftEnd}5`)
  sheet.mergeCells(`${rightStart}5:${lastColumn}5`)
  sheet.getCell('A5').value = `Generated: ${generatedAt.toLocaleString('en-GB')}`
  sheet.getCell(`${rightStart}5`).value = `Generated By: ${generatedBy} (${titleCase(role)})`
  sheet.getCell('A5').font = sheet.getCell(`${rightStart}5`).font = { name: 'Aptos', size: 10, color: { argb: COLORS.muted } }
  sheet.getCell(`${rightStart}5`).alignment = { horizontal: 'right' }
}

const styleHeader = row => {
  row.height = 30
  row.eachCell(cell => {
    cell.font = { name: 'Aptos', size: 10, bold: true, color: { argb: COLORS.white } }
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.header } }
    cell.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true }
    cell.border = thinBorder
  })
}

const styleDataRows = (sheet, firstRow, lastRow, columnCount) => {
  for (let rowNumber = firstRow; rowNumber <= lastRow; rowNumber += 1) {
    const row = sheet.getRow(rowNumber)
    row.height = 26
    for (let column = 1; column <= columnCount; column += 1) {
      const cell = row.getCell(column)
      cell.border = thinBorder
      cell.alignment = { vertical: 'middle', wrapText: true }
      cell.font = { name: 'Aptos', size: 10, color: { argb: COLORS.ink } }
      if ((rowNumber - firstRow) % 2 === 1) cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.stripe } }
    }
  }
}

const autoFitColumns = (sheet, minimums, maximums) => {
  sheet.columns.forEach((column, index) => {
    let width = minimums[index] || 12
    column.eachCell({ includeEmpty: true }, cell => {
      const value = cell.value instanceof Date ? 18 : String(cell.value?.richText ? cell.value.richText.map(item => item.text).join('') : cell.value ?? '')
      width = Math.max(width, Math.min(value.length + 2, maximums[index] || 38))
    })
    column.width = Math.min(width, maximums[index] || 38)
  })
}

exports.exportExcel = async (req, res, next) => {
  try {
    const data = await reportService.analytics(req.query, { includeRows: true })
    const workbook = new ExcelJS.Workbook()
    const generatedAt = new Date()
    const generatedBy = req.user?.name || req.user?.email || 'System User'
    const period = `${dateText(data.range.from)} - ${dateText(data.range.toInclusive)}`

    workbook.creator = generatedBy
    workbook.company = 'Visitor Pass Management System'
    workbook.created = generatedAt
    workbook.modified = generatedAt

    const summary = workbook.addWorksheet('Summary', { views: [{ showGridLines: false }] })
    addHeading(summary, 'H', 'Visitor Operations Report', period, generatedAt, generatedBy, req.user?.role)
    summary.addRow([])
    summary.addRow(['Summary Metric', 'Value'])
    styleHeader(summary.getRow(7))
    const metrics = [
      ['Total Visitors', data.summary.total],
      ['Approved', data.summary.approved],
      ['Rejected', data.summary.rejected],
      ['Pending', data.summary.pending],
      ['Checked In', data.summary.checkedIn],
      ['Checked Out', data.summary.checkedOut],
      ['Visitors Inside', data.summary.inside],
      ['Cancelled', data.summary.cancelled],
    ]
    metrics.forEach(metric => summary.addRow(metric))
    styleDataRows(summary, 8, 15, 2)
    summary.getColumn(2).numFmt = '#,##0'
    summary.getColumn(1).width = 30
    summary.getColumn(2).width = 18
    summary.pageSetup = { orientation: 'portrait', fitToPage: true, fitToWidth: 1, fitToHeight: 0 }
    summary.headerFooter.oddFooter = 'Visitor Pass Management System &L&D &T&RPage &P of &N'

    const details = workbook.addWorksheet('Visitor Details', { views: [{ state: 'frozen', ySplit: 7, showGridLines: false }] })
    addHeading(details, 'L', 'Visitor Detail Register', period, generatedAt, generatedBy, req.user?.role)
    details.addRow([])
    const headers = ['Visitor Name', 'Company', 'Mobile Number', 'Email', 'Host Employee', 'Department', 'Purpose', 'Visit Date', 'Expected Arrival', 'Check-In Time', 'Check-Out Time', 'Status']
    const headerRow = details.addRow(headers)
    styleHeader(headerRow)

    data.rows.forEach(visitor => {
      details.addRow([
        visitor.visitorName,
        visitor.companyName || '-',
        visitor.phone || '-',
        visitor.email || '-',
        visitor.employee?.name || '-',
        visitor.department?.name || '-',
        visitor.purpose,
        new Date(visitor.visitDate),
        visitor.expectedArrival || '-',
        visitor.checkedInAt ? new Date(visitor.checkedInAt) : null,
        visitor.checkedOutAt ? new Date(visitor.checkedOutAt) : null,
        titleCase(visitor.status),
      ])
    })

    const firstDataRow = 8
    const lastDataRow = 7 + data.rows.length
    if (data.rows.length) styleDataRows(details, firstDataRow, lastDataRow, headers.length)
    details.getColumn(3).numFmt = '@'
    details.getColumn(8).numFmt = 'dd-mmm-yyyy'
    details.getColumn(9).numFmt = '@'
    details.getColumn(10).numFmt = 'dd-mmm-yyyy hh:mm'
    details.getColumn(11).numFmt = 'dd-mmm-yyyy hh:mm'

    const totalRow = details.addRow(['Total Visitors', '', '', '', '', '', '', '', '', '', '', data.rows.length])
    details.mergeCells(`A${totalRow.number}:K${totalRow.number}`)
    totalRow.height = 28
    for (let column = 1; column <= headers.length; column += 1) {
      const cell = totalRow.getCell(column)
      cell.font = { name: 'Aptos', bold: true, color: { argb: COLORS.white } }
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.accent } }
      cell.border = thinBorder
      cell.alignment = { vertical: 'middle', horizontal: column === 12 ? 'center' : 'right' }
    }

    details.autoFilter = { from: 'A7', to: 'L7' }
    autoFitColumns(details, [20, 16, 16, 24, 20, 18, 26, 15, 17, 20, 20, 14], [28, 26, 20, 34, 28, 24, 42, 18, 20, 22, 22, 18])
    details.pageSetup = { orientation: 'landscape', paperSize: 8, fitToPage: true, fitToWidth: 1, fitToHeight: 0, repeatRows: '7:7', margins: { left: 0.25, right: 0.25, top: 0.45, bottom: 0.45, header: 0.2, footer: 0.2 } }
    details.headerFooter.oddFooter = 'Visitor Pass Management System &LTotal visitors: ' + data.rows.length + '&RPage &P of &N'

    const filename = `visitor-operations-report-${data.range.period}-${Date.now()}.xlsx`
    res.set({
      'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'Content-Disposition': `attachment; filename="${filename}"`,
    })
    await workbook.xlsx.write(res)
    res.end()
  } catch (error) {
    next(error)
  }
}
