const PDFDocument = require('pdfkit')
const reportService = require('../services/reportService')
const { ok } = require('../utils/response')

const COLORS = {
  ink: '#183247',
  header: '#284c63',
  accent: '#2f6f73',
  accentLight: '#e8f1f1',
  border: '#d4dee5',
  stripe: '#f5f8fa',
  muted: '#5f7180',
  white: '#ffffff',
}

const titleCase = value => String(value || '').replaceAll('_', ' ').replace(/\b\w/g, character => character.toUpperCase())
const dateText = date => new Date(date).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
const dateTimeText = value => value ? new Date(value).toLocaleString('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' }) : '-'

exports.getReport = async (req, res, next) => {
  try {
    const analytics = await reportService.analytics(req.query)
    const table = await reportService.paginatedRows(req.query, analytics.range)
    ok(res, {
      summary: analytics.summary,
      charts: analytics.charts,
      range: { period: analytics.range.period, from: analytics.range.from, to: analytics.range.toInclusive },
      visitors: table.items,
    }, 'Report loaded', table.meta)
  } catch (error) {
    next(error)
  }
}

const drawMetadata = (doc, data, generatedAt, generatedBy, role) => {
  const pageWidth = doc.page.width
  const margin = doc.page.margins.left
  const contentWidth = pageWidth - margin - doc.page.margins.right

  doc.rect(0, 0, pageWidth, 108).fill(COLORS.ink)
  doc.fillColor(COLORS.white).font('Helvetica-Bold').fontSize(22).text('Visitor Pass Management System', margin, 28)
  doc.fillColor('#cbd7de').font('Helvetica').fontSize(11).text('Visitor Operations Report', margin, 58)
  doc.fillColor('#cbd7de').fontSize(8.5).text(`Report period: ${dateText(data.range.from)} - ${dateText(data.range.toInclusive)}`, margin, 78)
  doc.text(`Generated: ${generatedAt.toLocaleString('en-GB')}`, pageWidth - margin - 290, 55, { width: 290, align: 'right' })
  doc.text(`Generated by: ${generatedBy} (${titleCase(role)})`, pageWidth - margin - 290, 74, { width: 290, align: 'right' })
  return { margin, contentWidth, y: 128 }
}

const drawSummary = (doc, data, startY, margin, contentWidth) => {
  doc.fillColor(COLORS.ink).font('Helvetica-Bold').fontSize(12).text('Report summary', margin, startY)
  const metrics = [
    ['Total Visitors', data.summary.total],
    ['Approved', data.summary.approved],
    ['Rejected', data.summary.rejected],
    ['Pending', data.summary.pending],
    ['Checked In', data.summary.checkedIn],
    ['Checked Out', data.summary.checkedOut],
    ['Visitors Inside', data.summary.inside],
    ['Cancelled', data.summary.cancelled],
  ]
  const gap = 8
  const width = (contentWidth - gap * 3) / 4
  const height = 48
  metrics.forEach(([label, value], index) => {
    const column = index % 4
    const row = Math.floor(index / 4)
    const x = margin + column * (width + gap)
    const y = startY + 22 + row * (height + gap)
    doc.roundedRect(x, y, width, height, 4).fillAndStroke(index === 0 ? COLORS.accentLight : COLORS.white, COLORS.border)
    doc.fillColor(COLORS.muted).font('Helvetica').fontSize(7).text(label.toUpperCase(), x + 10, y + 9, { width: width - 20 })
    doc.fillColor(COLORS.ink).font('Helvetica-Bold').fontSize(16).text(String(value || 0), x + 10, y + 23, { width: width - 20 })
  })
  return startY + 22 + (height + gap) * 2 + 12
}

const columns = [
  { label: 'Visitor Name', key: 'visitorName', width: 102 },
  { label: 'Company', key: 'companyName', width: 82 },
  { label: 'Mobile Number', key: 'phone', width: 78 },
  { label: 'Email', key: 'email', width: 118 },
  { label: 'Host Employee', key: 'host', width: 100 },
  { label: 'Department', key: 'department', width: 82 },
  { label: 'Purpose', key: 'purpose', width: 112 },
  { label: 'Visit Date', key: 'visitDate', width: 72 },
  { label: 'Visit Schedule', key: 'visitSchedule', width: 69 },
  { label: 'Check-In Time', key: 'checkedInAt', width: 87 },
  { label: 'Check-Out Time', key: 'checkedOutAt', width: 87 },
  { label: 'Status', key: 'status', width: 72 },
]

const rowValues = visitor => ({
  visitorName: visitor.visitorName || '-',
  companyName: visitor.companyName || '-',
  phone: visitor.phone || '-',
  email: visitor.email || '-',
  host: visitor.employee?.name || '-',
  department: visitor.department?.name || '-',
  purpose: visitor.purpose || '-',
  visitDate: dateText(visitor.visitDate),
  visitSchedule: visitor.expectedArrival
    ? `${visitor.expectedArrival}${visitor.expectedDeparture ? ` - ${visitor.expectedDeparture}` : ''}`
    : '-',
  checkedInAt: dateTimeText(visitor.checkedInAt),
  checkedOutAt: dateTimeText(visitor.checkedOutAt),
  status: titleCase(visitor.status),
})

const drawTableHeader = (doc, y, margin) => {
  let x = margin
  columns.forEach(column => {
    doc.rect(x, y, column.width, 30).fillAndStroke(COLORS.header, COLORS.border)
    doc.fillColor(COLORS.white).font('Helvetica-Bold').fontSize(6.6).text(column.label, x + 4, y + 8, { width: column.width - 8, height: 17, align: 'center' })
    x += column.width
  })
  return y + 30
}

const drawTableRow = (doc, visitor, index, y, margin) => {
  const values = rowValues(visitor)
  const rowHeight = 34
  let x = margin
  columns.forEach(column => {
    doc.rect(x, y, column.width, rowHeight).fillAndStroke(index % 2 === 1 ? COLORS.stripe : COLORS.white, COLORS.border)
    doc.fillColor(column.key === 'status' ? COLORS.accent : COLORS.ink)
      .font(['visitorName', 'status'].includes(column.key) ? 'Helvetica-Bold' : 'Helvetica')
      .fontSize(6.4)
      .text(String(values[column.key]), x + 4, y + 7, { width: column.width - 8, height: 21, ellipsis: true })
    x += column.width
  })
  return y + rowHeight
}

exports.exportPdf = async (req, res, next) => {
  try {
    const data = await reportService.analytics(req.query, { includeRows: true })
    const generatedAt = new Date()
    const generatedBy = req.user?.name || req.user?.email || 'System User'
    const filename = `visitor-operations-report-${data.range.period}-${Date.now()}.pdf`
    res.set({ 'Content-Type': 'application/pdf', 'Content-Disposition': `attachment; filename="${filename}"` })

    const doc = new PDFDocument({
      size: 'A3',
      layout: 'landscape',
      margin: 34,
      bufferPages: true,
      info: { Title: 'Visitor Operations Report', Author: generatedBy, Subject: 'Visitor operations and detail register' },
    })
    doc.pipe(res)

    const metadata = drawMetadata(doc, data, generatedAt, generatedBy, req.user?.role)
    let y = drawSummary(doc, data, metadata.y, metadata.margin, metadata.contentWidth)
    doc.fillColor(COLORS.ink).font('Helvetica-Bold').fontSize(12).text('Visitor details', metadata.margin, y)
    y = drawTableHeader(doc, y + 18, metadata.margin)

    data.rows.forEach((visitor, index) => {
      if (y + 34 > doc.page.height - 46) {
        doc.addPage()
        y = drawTableHeader(doc, 34, metadata.margin)
      }
      y = drawTableRow(doc, visitor, index, y, metadata.margin)
    })

    if (!data.rows.length) {
      doc.rect(metadata.margin, y, metadata.contentWidth, 42).fillAndStroke(COLORS.stripe, COLORS.border)
      doc.fillColor(COLORS.muted).font('Helvetica').fontSize(9).text('No visitors matched the selected report filters.', metadata.margin + 12, y + 16)
      y += 42
    }

    if (y + 34 > doc.page.height - 46) {
      doc.addPage()
      y = 34
    }
    doc.rect(metadata.margin, y, metadata.contentWidth, 28).fill(COLORS.accent)
    doc.fillColor(COLORS.white).font('Helvetica-Bold').fontSize(9).text('Total visitors', metadata.margin + 10, y + 9)
    doc.text(String(data.rows.length), metadata.margin, y + 9, { width: metadata.contentWidth - 10, align: 'right' })

    const pages = doc.bufferedPageRange()
    for (let index = 0; index < pages.count; index += 1) {
      doc.switchToPage(index)
      doc.fillColor(COLORS.muted).font('Helvetica').fontSize(7)
        .text(`Visitor Pass Management System  |  Total visitors: ${data.rows.length}  |  Page ${index + 1} of ${pages.count}`, 34, doc.page.height - 25, { width: doc.page.width - 68, align: 'center' })
    }
    doc.end()
  } catch (error) {
    next(error)
  }
}
